on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Excavate
    uses: ScoopInstaller/Scoop-GithubActions@main-lin
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SKIP_UPDATED: '1'
