on:
  pull_request:
    types: [ opened ]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: PullRequestHandler
      uses: ScoopInstaller/Scoop-GithubActions@main-lin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
